#!/usr/bin/env node
// theme/build-theme.mjs — the ENTIRE reskin mechanism for cloning this dashboard
// to a new business. Usage:
//
//   node theme/build-theme.mjs <brandHex> [businessName]
//
// Example:  node theme/build-theme.mjs "#7B5CE0" "AI Funding Solutions"
//
// What it does:
//   1. Derives a validated 2-color categorical palette (series-1 = the brand hue
//      itself, series-2 = an auto-searched colorblind-safe partner) for both
//      light and dark mode, using the same OKLCH checks as the dataviz skill.
//   2. Derives brand-tinted dark/light surfaces (the "premium dark UI" look) and
//      a light->dark gradient ramp for the hero chart.
//   3. Keeps status colors (good/warning/critical) FIXED — never derived from
//      brand, per the design system's own rule that status colors must stay
//      distinct from any series and never be re-themed per client.
//   4. Writes theme/themes/<slug>.json (the resolved values, for the record)
//      AND public/theme.css (what the dashboard actually loads).
//
// To reskin an existing clone for a new business: run this one command with
// the new brand hex, then redeploy. Nothing else in the dashboard changes.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { deriveSeries1, deriveSeries2, deriveRamp, tintSurface, validatePair, contrast } from "./lib.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const brandHex = process.argv[2];
const businessName = process.argv[3] || "Business";
if (!brandHex || !/^#?[0-9a-fA-F]{6}$/.test(brandHex)) {
  console.error('usage: node build-theme.mjs "#RRGGBB" ["Business Name"]');
  process.exit(1);
}
const brand = brandHex.startsWith("#") ? brandHex : "#" + brandHex;

// ── fixed status palette — never derived from brand ──────────────────────────
const STATUS = { good: "#0ca30c", warning: "#fab219", critical: "#d03b3b" };

function buildMode(mode) {
  const series1 = deriveSeries1(brand, mode);
  const series2 = deriveSeries2(brand, mode);
  const check = validatePair(series1, series2, mode, mode === "dark" ? tintSurface(brand, 0.17, 0.028) : "#fcfcfb");

  if (mode === "dark") {
    return {
      series1, series2,
      page: tintSurface(brand, 0.09, 0.022),
      surface1: tintSurface(brand, 0.17, 0.028),
      textPrimary: "#ffffff",
      textSecondary: "#c9c6e0",
      textMuted: "#8f8ba8",
      grid: tintSurface(brand, 0.26, 0.03),
      baseline: tintSurface(brand, 0.34, 0.035),
      border: "rgba(255,255,255,0.10)",
      cardBorderGlow: tintSurface(brand, 0.40, 0.09),
      check,
    };
  }
  return {
    series1, series2,
    page: tintSurface(brand, 0.975, 0.006),
    surface1: tintSurface(brand, 0.99, 0.004),
    textPrimary: "#0b0b0b",
    textSecondary: "#52514e",
    textMuted: "#898781",
    grid: "#e1e0d9",
    baseline: "#c3c2b7",
    border: "rgba(11,11,11,0.10)",
    cardBorderGlow: tintSurface(brand, 0.6, 0.10),
    check,
  };
}

const dark = buildMode("dark");
const light = buildMode("light");

const theme = {
  businessName,
  brandInput: brand,
  generatedBy: "theme/build-theme.mjs",
  status: STATUS,
  heroRampDark: deriveRamp(brand, 5, 0.62, 0.22),
  heroRampLight: deriveRamp(brand, 5, 0.88, 0.42),
  dark,
  light,
};

// ── validation report ──────────────────────────────────────────────────────
console.log(`\nTheme for "${businessName}" from brand ${brand}\n`);
for (const mode of ["dark", "light"]) {
  const t = theme[mode];
  console.log(`[${mode}] series1=${t.series1}  series2=${t.series2}`);
  t.check.report.forEach(line => console.log(`   ${t.check.ok ? "  " : "! "}${line}`));
  console.log(`   -> ${t.check.ok ? "PASS" : "CHECK ABOVE — floor/relief bands still usable with direct labels"}\n`);
}

// ── write theme/themes/<slug>.json ──────────────────────────────────────────
const slug = businessName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "default";
const themesDir = path.join(__dirname, "themes");
fs.mkdirSync(themesDir, { recursive: true });
fs.writeFileSync(path.join(themesDir, `${slug}.json`), JSON.stringify(theme, null, 2));
console.log(`Wrote theme/themes/${slug}.json`);

// ── write public/theme.css ──────────────────────────────────────────────────
function cssVars(t, extra = {}) {
  return [
    `--page: ${t.page};`,
    `--surface-1: ${t.surface1};`,
    `--text-primary: ${t.textPrimary};`,
    `--text-secondary: ${t.textSecondary};`,
    `--text-muted: ${t.textMuted};`,
    `--grid: ${t.grid};`,
    `--baseline: ${t.baseline};`,
    `--border: ${t.border};`,
    `--card-glow: ${t.cardBorderGlow};`,
    `--series-1: ${t.series1};`,
    `--series-2: ${t.series2};`,
    `--accent: ${t.series1};`,
    ...Object.entries(extra).map(([k, v]) => `${k}: ${v};`),
  ].join("\n    ");
}

const css = `/* AUTO-GENERATED by theme/build-theme.mjs from brand ${brand} — do not hand-edit.
   To reskin: node theme/build-theme.mjs "#newhex" "Business Name" && redeploy. */
:root {
    color-scheme: dark;
    ${cssVars(dark, { "--hero-ramp-0": dark ? theme.heroRampDark[0] : "", "--hero-ramp-1": theme.heroRampDark[1], "--hero-ramp-2": theme.heroRampDark[2], "--hero-ramp-3": theme.heroRampDark[3], "--hero-ramp-4": theme.heroRampDark[4] })}
    --status-good: ${STATUS.good};
    --status-warning: ${STATUS.warning};
    --status-critical: ${STATUS.critical};
}
:root[data-theme="light"] {
    color-scheme: light;
    ${cssVars(light, { "--hero-ramp-0": theme.heroRampLight[0], "--hero-ramp-1": theme.heroRampLight[1], "--hero-ramp-2": theme.heroRampLight[2], "--hero-ramp-3": theme.heroRampLight[3], "--hero-ramp-4": theme.heroRampLight[4] })}
}
`;

const publicDir = path.join(__dirname, "..", "public");
fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(path.join(publicDir, "theme.css"), css);
console.log(`Wrote public/theme.css`);
